---
- hosts: "localhost"
  connection: "local"
  user: "root"
#  pre_tasks:
#    - name: "read retry file from last run"
#      shell: "cat ~/inventories/retry/ssh.key.deploy.retry; true"
#      register: "ssh_retry"
#    - name: "set a commend for monitoring"
#      lineinfile:
#        path: "~/inventories/retry/ssh.key.deploy.retry"
#        line: "==> PlayBook 'ssh.key.deploy' currently running, please check if finish\n not success hosts from last run was:"
#        regexp:  "==> PlayBook 'ssh.key.deploy' currently running, please check if finish\n not success hosts from last run was:"
#        insertbefore: "BOF"
#      register: "monitoring_msg"
#      when: "ssh_retry.stdout|default('') != ''"
  roles:
#    - { role: "ansible.build.new.inventory", tags: "ansible.build.new.inventory" }
    - { role: "ssh.key.get", tags: "ssh.key.get" }
  tags: "getsshkeysfromAD"
  
- hosts: "get_ssh_keys"
  user: "root"
  serial: "25%"
  strategy: "free"
  roles:
    - { role: "ssh.key.remove_perl_script", tags: "ssh.key.remove_perl_script" }
    - { role: "ssh.key.deploy", tags: "ssh.key.deploy" }
  tags: "deploysshkeys"
#  post_tasks:
#    - name: "remove retry file"
#      file:
#        path: "~/inventories/retry/ssh.key.deploy.retry"
#        state: "absent"
#      delegate_to: "localhost"
#      run_once: "true"
