ALTER profile DEFAULT LIMIT PASSWORD_LIFE_TIME unlimited;
ALTER profile DEFAULT LIMIT PASSWORD_GRACE_TIME unlimited;
ALTER system set OPTIMIZER_INDEX_CACHING = 80;
ALTER system set OPTIMIZER_INDEX_COST_ADJ = 25;
ALTER system SET audit_trail=NONE SCOPE=SPFILE;
ALTER SYSTEM SET archive_lag_target=1800;
ALTER SYSTEM SET UNDO_RETENTION = 3600;
spool dbid.corpus
SELECT DBID FROM V$DATABASE;
spool off
exit;
