---
# tasks file for roles/censhare.serviceclient.systemd
- name: "PreAction: - extract start/stop scripts from GIT repo -> s2s installer"
  shell: "cd ~/tmp && tar -zxf {{git_itservices}}/scripts/censhare/s2s-install-update.tar.gz s2s/sysconfig.tpl/css_serviceclient.tpl"
  delegate_to: "localhost"
  run_once: "true"
  tags: "localTASK"
  register: "localTASK"

- name: "copy s2s files"
  copy:
    src: "~/tmp/s2s/sysconfig.tpl/css_serviceclient.tpl"
    dest: "/etc/sysconfig/css_serviceclient"
    mode: "0755"
  when: "localTASK|success"
  register: "cpcssSCstartfiles"
  tags: "cpcssSCstartfiles"

- name: "write service file for systemd"
  blockinfile:
    path: "/etc/systemd/system/censhare.serviceclient.service"
    owner: "root"
    group: "root"
    mode: "0644"
    create: "yes"
    block: |
      [Unit]
      Description=censhare ServiceClient
      Documentation=https://ecosphere.censhare.com/en/Search?s.text=censhare=server
      After=censhare.server.service
      
      [Service]
      EnvironmentFile=/etc/sysconfig/css_serviceclient
      ExecStart=/opt/corpus/service-client/serviceclient.sh start
      ExecStop=/opt/corpus/service-client/serviceclient.sh stop
      Restart=on-failure
      Type=forking
      PIDFile=/opt/corpus/service-client/run/serviceclient.pid
      TimeoutStartSec=600
      
      [Install]
      WantedBy=default.target
      Alias=serviceclient.service
  when: "cpcssSCstartfiles|success"
  register: "wrSCsystemdfile"
  tags: "wrSCsystemdfile"
  
- name: "cleanup locally"
  file:
    path: "~/tmp/s2s"
    state: "absent"
  delegate_to: "localhost"
  run_once: "true"
