---
# tasks file for roles/solaris.smf.rbac.censhare
- name: "add RBAC auth string in Security file"
  lineinfile:
    dest: "/etc/security/auth_attr"
    line: "{{auth_attr}}{{auth_attr_desc}}"
    regexp: "{{auth_attr}}"
  register: "addRBAC4cen"
  tags: "SMF RBAC"

- name: "add RBAC settings to SMF services for censhare/censhare"
  command: "svccfg -s censhare/{{item.service}} setprop general/{{item.smf}}_authorization=astring: {{auth_attr}}"
  with_items:
  - { service: 'server', smf: 'action' }
  - { service: 'server', smf: 'value' }
  when: "addRBAC4cen|success"
  tags: "SMF RBAC"

- name: "RBAC add privileges to censhare user"
  command: "usermod -A {{auth_attr}} {{cen_user}}"
  when: "addRBAC4cen|success"
  tags: "SMF RBAC"
