---
# tasks file for roles/censhare.install.nginx.rpm
- name: "install and configure nginx"
  block:
    - name: "add repository to host"
      blockinfile:
        path: "/etc/yum.repos.d/nginx.repo"
        create: "yes"
        backup: "yes"
        block: |
          [nginx]
          name=nginx repo
          baseurl=http://nginx.org/packages/{{ansible_distribution|lower}}/{{ansible_distribution_major_version}}/$basearch/
          gpgcheck=0
          enabled=1
      register: "addnginxrepo"
      tags: "addnginxrepo"
      when: "ansible_distribution == 'CentOS'"
    
    - name: "install/update nginx"
      yum:
        name: "nginx"
        state: "latest"
      register: "instnginx"
      tags: "instnginx"
      when: "addnginxrepo|success"
    
    - name: "deploy nginx censhare default config"
      template:
        src: "nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        group: "root"
        owner: "root"
      register: "nginxconfig"
      tags: "nginxconfig"
      when: "instnginx|success"
      #notify: "start nginx"
