---
# tasks file for roles/censhare.v4-webclient.systemd
- name: "PreAction: - extract start/stop scripts from GIT repo -> s2s installer"
  shell: "cd ~/tmp && tar -zxf {{git_itservices}}/scripts/censhare/s2s-install-update.tar.gz s2s/sysconfig.tpl/css_jetty.tpl"
  delegate_to: "localhost"
  tags: "localTASK"
  register: "localTASK"

- name: "copy s2s files"
  copy:
    src: "~/tmp/s2s/sysconfig.tpl/css_jetty.tpl"
    dest: "/etc/sysconfig/css_jetty"
    mode: "0755"
  when: "localTASK|success"
  register: "cpcssstartfiles"
  tags: "cpcssstartfiles"

- name: "write service file for systemd"
  blockinfile:
    path: "/etc/systemd/system/css_jetty.service"
    owner: "root"
    group: "root"
    mode: "0644"
    create: "yes"
    block: |
      [Unit]
      Description=censhare server
      Documentation=https://ecosphere.censhare.com/en/Search?s.text=censhare=webclient
      After=censhare.service
      
      [Service]
      EnvironmentFile=/etc/sysconfig/css_jetty
      ExecStart=/opt/corpus/css/bin/css_jetty.rc start
      ExecStop=/opt/corpus/css/bin/css_jetty.rc stop
      Restart=on-failure
      Type=forking
      RestartSec=15s
      PIDFile=/var/run/jetty
      TimeoutStartSec=600
      
      [Install]
      WantedBy=default.target
      Alias=censhare_webclient.service
  when: "cpcssstartfiles|success"
  register: "wrsystemdfile"
  tags: "wrsystemdfile"
#  notify: "start css_jetty server" ### commented because of we have just a systemd role, no webclient install role
  
- name: "cleanup locally"
  file:
    path: "~/tmp/s2s"
    state: "absent"
  delegate_to: "localhost"
  run_once: "true"