---
# handlers file for roles/oracle.db.install.root.sh
- name: "start oracle db"
  service:
    name: "censhare/ora_censhare:default"
    state: "started"
    enabled: "yes"
- name: "start lsnrctl"
  service:
    name: "censhare/ora_lsnr:default"
    state: "started"
    enabled: "yes"
  tags: "startlsnr"
