# first and second instance, assume that is prod and test system
---
ngzp:                 "ns-ora-0{{srv_vlan}}0{{sto_vlan}}-{{item.value.instance}}"
custname:             "corode"
network_srv:          "10.130.4.97/27"
network_sto:          "10.131.4.97/27"
srv_vlan:             "737"
sto_vlan:             "957"
SaaS_ID:              "07370957"
tpm_project_id:       "454"
Install_Ticket:       "3449757"
CustomerName:         "Coroplast"
ngz:
  corode-01-prod:
    name:             "corode"
    instance_type:    "prod"
    instance:         "01"
    ip_srv:           "10.130.4.98/27"
    ip_sto:           "10.131.4.98/27"
    sys_mem:          "5"
    sys_cpu:          "100"
    censhare_version: "stable/latest"
  corode-02-test:
    name:             "corode"
    instance_type:    "test"
    instance:         "02"
    ip_srv:           "10.130.4.99/27"
    ip_sto:           "10.131.4.99/27"
    sys_mem:          "5"
    sys_cpu:          "100"
    censhare_version: "stable/latest"
# first and second instance, assume that is prod and test system
